/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import { Project } from './types';

import {
  Backup as BackupIcon,
  FolderSpecial as FolderSpecialIcon,
  LibraryMusic as LibraryMusicIcon,
  ListAlt as ListAltIcon,
  ManageSearch as ManageSearchIcon,
  PlayCircle as PlayCircleIcon,
  QueueMusic as QueueMusicIcon,
  QueuePlayNext as QueuePlayNextIcon,
  SportsBasketball as SportsBasketballIcon,
  Tag as TagIcon,
  Thermostat as ThermostatIcon,
} from '@mui/icons-material';

export const PROJECTS: Project[] = [
  {
    id: 1,
    title: 'Music Stats',
    cardIcon: ListAltIcon,
    inspiration: 'I love Spotify Wrapped and wanted to create a similar experience for my own music listening habits that I could access anytime. There were other apps that did this, but they were either too expensive or too clunky to use. I wanted something simple, easy to use, effective, and pleasing to the eye.',
    shortDescription: 'An iOS app that tells you your top songs and artists on Spotify anytime you want',
    longDescription: 'This application leverages Spotify\'s Web API to fetch user listening data and presents it in a visually appealing way. Users can view their top song and artists over different time periods, creating a personalized music experience. It also includes Keychain support for secure storage of access tokens, ensuring user data is protected, and streamlining the login process.',
    technologies: ['XCode', 'Swift', 'SwiftUI', 'Spotify Web API', 'Keychain'],
    images: [
      './images/Music Stats 1.png',
      './images/Music Stats 2.png',
      './images/Music Stats 3.png'
    ],
    video: './screen recordings/Music Stats Screen Recording.mp4',
    phase: 'Maintenance & Support',
    githubUrl: 'https://github.com/BrandonLC2020/Music-Stats-iOS',
  },
  {
    id: 2,
    title: 'Spotify Stats Monthly Snapshot Script',
    cardIcon: BackupIcon,
    inspiration: 'I love Spotify Wrapped and wanted to track my own listening habits over time. In particular, I wanted to build my own database of this data, possibly to use in other projects or perform my own analysis.',
    shortDescription: 'A script that generates monthly stats for your Spotify listening habits',
    longDescription: 'This script utilizes Spotify\'s Web API to gather and analyze user listening data on a monthly basis. It provides insights into top tracks and top artists, allowing me to reflect on my own music preferences over time. The script is designed to be run easily and automatically each month using AWS Lambda and EventBridge.',
    technologies: ['AWS', 'AWS Lambda', 'AWS EventBridge', 'AWS Secrets Manager', 'AWS Aurora', 'Spotify Web API', 'Python', 'MySQL'],
    phase: 'Maintenance & Support',
    githubUrl: 'https://github.com/BrandonLC2020/PersonalSpotifyStatsBackup',
  },
  {
    id: 3,
    title: 'Redirect URI Inspector',
    cardIcon: ManageSearchIcon,
    inspiration: 'I was working on another project that dealt with sending parameters via redirect URIs and wanted to create a tool that helps developers easily inspect and debug these redirect URIs. This tool aims to simplify the process of verifying and testing redirect URIs for various applications.',
    shortDescription: 'A web app for inspecting and testing redirect URIs',
    longDescription: 'This web application allows developers to input their redirect URIs and inspect the parameters being sent. It provides a user-friendly interface for testing and debugging redirect URIs, making it easier to identify issues and ensure proper functionality. It also records a history of inspected URIs for future reference.',
    technologies: ['AWS','AWS S3', 'AWS CloudFront', 'AWS DynamoDB', 'AWS Lambda', 'AWS API Gateway', 'React', 'TypeScript', 'Material-UI', 'Vite'],
    images: [
      './images/Redirect Inspector 1.png',
      './images/Redirect Inspector 2.png'
    ],
    video: './screen recordings/Redirect Inspector Screen Recording.mp4',
    phase: 'Maintenance & Support',
    githubUrl: 'https://github.com/BrandonLC2020/PersonalRedirectInspectorWebApp',
  },
  {
    id: 4,
    title: 'Dual Weather',
    cardIcon: ThermostatIcon,
    inspiration: 'I regularly chat with friends who live in different locations and use the metric system. I wanted to create a simple weather app that shows the weather for a location in both Fahrenheit and Celsius, making it easy to communicate and understand the weather each of us were experiencing.',
    shortDescription: 'An iOS app for displaying weather in multiple units',
    longDescription: 'This application allows users to input a location and view the current weather in both Fahrenheit and Celsius. It provides a user-friendly interface, displaying both temperature units, making it easier to understand the weather regardless of the measurement system used. Additionally, it includes features like location search and saving favorite locations using Firebase Firestore for persistent storage. Furthermore, it includes a temperature conversion tool, allowing users to convert temperatures between Fahrenheit and Celsius easily.',
    technologies: ['XCode', 'Swift', 'SwiftUI', 'WeatherKit', 'CoreLocation', 'Firebase', 'Firestore'],
    images: [
      './images/Dual Weather 1.png',
      './images/Dual Weather 2.png',
      './images/Dual Weather 3.png',
      './images/Dual Weather 4.png',
      './images/Dual Weather 5.png'
    ],
    video: './screen recordings/Dual Weather Screen Recording.mp4',
    phase: 'Maintenance & Support',
    githubUrl: 'https://github.com/BrandonLC2020/Dual-Weather-iOS',
  },
  {
    id: 5,
    title: 'ListenList',
    cardIcon: QueueMusicIcon,
    inspiration: 'I\'m an avid music listener and wanted to create a tool that allows me to create a collection of artists and their songs that I want to listen to. My Spotify library was getting cluttered with songs I wanted to listen to, but didn\'t want to add to my library. I wanted a way to keep track of these songs and artists without cluttering my library.',
    shortDescription: 'An iOS app for organizing music you want to listen to',
    longDescription: 'This application allows users to create and manage a collection of artists, albums, and songs they want to listen to. It provides a user-friendly interface for searching, adding, and removing, artists, albums, and songs from the ListenList, making it easier to curate and collect music to listen to without cluttering the main library.',
    technologies: ['XCode', 'Swift', 'SwiftUI', 'Spotify Web API', 'Keychain', 'Firebase', 'Firestore'],
    images: [
      './images/ListenList 1.png',
      './images/ListenList 2.png',
      './images/ListenList 3.png',
      './images/ListenList 4.png',
      './images/ListenList 5.png'
    ],
    video: './screen recordings/ListenList Screen Recording.mp4',
    phase: 'Maintenance & Support',
    githubUrl: 'https://github.com/BrandonLC2020/ListenList-iOS',
  },   
  {
    id: 6,
    title: 'March Madness Stats',
    cardIcon: SportsBasketballIcon,
    inspiration: 'I love college basketball and wanted to create a tool that provides detailed statistics and insights about NCAA Men\'s Basketball. I wanted to practice building a backend service using Java and Spring Boot, as well as creating a frontend using React and TypeScript. I want this app to be a useful resource for college basketball fans, analysts, and enthusiasts who want to explore and analyze season tournament data.',
    shortDescription: 'A web app for exploring NCAA Men\'s Basketball statistics',
    longDescription: 'This web application allows users to explore and analyze NCAA Men\'s Basketball statistics, including team and player performance data. It provides a user-friendly interface for visualizing stats, making it easier for fans and analysts to gain insights into the game.',
    technologies: ['Java', 'Maven', 'Spring Boot', 'React', 'TypeScript', 'Material UI', 'Plotly', 'College Basketball Data API'],
    phase: 'Implementation',
    githubUrl: 'https://github.com/BrandonLC2020/MarchMadnessStats',
  },
  {
    id: 7,
    title: 'Now Playing',
    cardIcon: PlayCircleIcon,
    inspiration: 'I often sleep with music playing in the background and with my iPhone in StandBy mode. Spotify doesn\'t currently show the currently playing song in StandBy mode, which is frustrating when wanting to quickly change the song. I wanted to create a simple app that shows the currently playing song in StandBy mode, so I can easily see what\'s playing without having to unlock my phone or open the Spotify app.',
    shortDescription: 'An iOS app for displaying and controlling the currently playing song in StandBy mode',
    longDescription: 'This application allows users to see the currently playing song from Spotify in StandBy mode on their iPhone. It provides a simple interface for displaying the song information, making it easier for users to quickly identify and change the song without unlocking their phone or opening the Spotify app.',
    technologies: ['XCode', 'Swift', 'SwiftUI', 'Spotify iOS SDK'],
    phase: 'Implementation',
    githubUrl: 'https://github.com/BrandonLC2020/NowPlaying',
  },
  {
    id: 8,
    title: 'WatchList',
    cardIcon: QueuePlayNextIcon,
    inspiration: 'I\'m an avid movie and TV show watcher and wanted to create a tool that allows me to create a collection of movies and TV shows that I want to watch. My streaming services\' watchlists were getting cluttered with movies and shows I wanted to watch, but didn\'t want to add to my watchlist. I wanted a way to keep track of these movies and shows without cluttering my streaming services\' watchlists.',
    shortDescription: 'A web app for managing a personal watchlist of movies and TV shows',
    longDescription: 'This web application allows users to create and manage a personal watchlist of movies and TV shows. It provides a user-friendly interface for adding, removing, and organizing titles, making it easier for users to keep track of what they want to watch without cluttering their streaming services\' watchlists.',
    technologies: ['React', 'TypeScript', 'Material-UI','TMDB API', '.NET', 'C#'],
    phase: 'Planning & Requirements Analysis',
    githubUrl: 'https://github.com/BrandonLC2020/WatchList-React-App',
  },
  {
    id: 9,
    title: 'Spotify Stats Web App',
    cardIcon: LibraryMusicIcon,
    inspiration: 'I wanted to create a tool that lets me easily access my Spotify listening stats in a web app format, similar to Spotify Wrapped. This tool aims to provide a simple and effective way to view my top songs and artists over different time periods, enhancing my music listening experience. In particular, I wanted to connect to my existing Spotify Stats database that I built using AWS services.',
    shortDescription: 'A web app for viewing Spotify listening stats',
    longDescription: 'This web application allows users to view their Spotify listening stats in a visually appealing way. It connects to a backend service that retrieves user listening data from a database, providing insights into top tracks and artists over different time periods. The app is designed to be simple and easy to use, enhancing the overall music experience.',
    technologies: ['React', 'TypeScript', 'Material-UI', 'Spotify Web API', 'Ruby', 'AWS', 'AWS Aurora', 'MySQL'],
    phase: 'Planning & Requirements Analysis',
    githubUrl: 'https://github.com/BrandonLC2020/PersonalSpotifyStatsWebApp',
  },
  {
    id: 10,
    title: 'Tic-Tac-Toe Game',
    cardIcon: TagIcon,
    inspiration: 'In my AP Computer Science class back in high school, I created a simple Tic-Tac-Toe game you can play in the console. I wanted to revisit this project and create a GUI version of the game using Java Swing, enhancing the user experience with a graphical interface.',
    shortDescription: 'A GUI version of the classic Tic-Tac-Toe game',
    longDescription: 'This web application is a graphical version of the classic Tic-Tac-Toe game. It allows users to play the game against another player or the computer, providing an engaging and interactive experience. The game features a simple and intuitive interface, making it easy for players of all ages to enjoy.',
    technologies: ['Java', 'Java Swing'],
    phase: 'Implementation',
    githubUrl: 'https://github.com/BrandonLC2020/TicTacToeGUI',
  },
  {
    id: 11,
    title: 'Developer Portfolio',
    cardIcon: FolderSpecialIcon,
    inspiration: 'I wanted to create a personal portfolio website to showcase my projects, skills, and experiences as a software engineer. For a while, I had been looking at using Wix or Squarespace to create a portfolio, but I wanted to build it myself from scratch to practice my web development skills and have full control over the design and functionality.',
    shortDescription: 'Yes, the website you\'re currently on! A personal portfolio website to showcase my projects and skills',
    longDescription: 'This portfolio website serves as a comprehensive showcase of my work as a software engineer. It highlights my projects, skills, and experiences, providing visitors with insights into my capabilities and expertise.',
    technologies: ['React', 'TypeScript', 'Material-UI', 'Vite'],
    phase: 'Maintenance & Support',
    githubUrl: 'https://github.com/BrandonLC2020/Portfolio',
  } 
];